#!/bin/bash

### BEGIN INIT INFO
# Provides:          tama
# Required-Start:    $remote_fs $network $time 
# Required-Stop:     $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start tama at boot time
# Description:       Enable service provided by tamaclient from the tama suite.
### END INIT INFO

PROG="tamaclient"
PROG_PATH="/usr/local/sbin/tama"
PID_PATH="/var/run"

start() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        ## Program is running, exit with error.
        echo "Error! $PROG is currently running!" 1>&2
        exit 1
    else
        ## Change from /dev/null to something like /var/log/$PROG if you want to save output.
            $PROG_PATH/$PROG.py $PROG_ARGS 2>&1 >/var/log/tama.log &
	    #/etc/init.d/rsyslog restart
        echo "$PROG started"
    fi
}

stop() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        ## Program is running, so stop it
        kill -SIGTERM `cat $PID_PATH/$PROG.pid ` 
        sleep 5s;
        if [ -e "$PID_PATH/$PROG.pid" ]; then
            echo "Impossible to stop $PROG"
        else
            echo "$PROG stopped"
        fi
	#/etc/init.d/rsyslog restart
    else
        ## Program is not running, exit with error.
        echo "Error! $PROG not started!" 1>&2
        exit 1
    fi
}

## Check to see if we are running as root first.
## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|restart}" 1>&2
        exit 1
    ;;
esac
